// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class get_register_page_req;
@class get_register_page_reqBuilder;
@class get_register_page_rsp;
@class get_register_page_rspBuilder;
@class register_getsms_num_req;
@class register_getsms_num_reqBuilder;
@class register_getsms_num_rsp;
@class register_getsms_num_rspBuilder;
@class register_req;
@class register_reqBuilder;
@class register_rsp;
@class register_rspBuilder;
@class register_set_passwd_req;
@class register_set_passwd_reqBuilder;
@class register_set_passwd_rsp;
@class register_set_passwd_rspBuilder;



@interface ZsappImMsgRegisterRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface get_register_page_req : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (get_register_page_reqBuilder*) builder;
+ (get_register_page_reqBuilder*) builder;
+ (get_register_page_reqBuilder*) builderWithPrototype:(get_register_page_req*) prototype;
- (get_register_page_reqBuilder*) toBuilder;

+ (get_register_page_req*) parseFromData:(NSData*) data;
+ (get_register_page_req*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (get_register_page_req*) parseFromInputStream:(NSInputStream*) input;
+ (get_register_page_req*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (get_register_page_req*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (get_register_page_req*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface get_register_page_reqBuilder : PBGeneratedMessageBuilder {
@private
  get_register_page_req* resultGetRegisterPageReq;
}

- (get_register_page_req*) defaultInstance;

- (get_register_page_reqBuilder*) clear;
- (get_register_page_reqBuilder*) clone;

- (get_register_page_req*) build;
- (get_register_page_req*) buildPartial;

- (get_register_page_reqBuilder*) mergeFrom:(get_register_page_req*) other;
- (get_register_page_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (get_register_page_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define get_register_page_rsp_str_secure_pic_url @"strSecurePicUrl"
#define get_register_page_rsp_bytes_valide_code_sig @"bytesValideCodeSig"
#define get_register_page_rsp_bytes_pic_binary @"bytesPicBinary"
@interface get_register_page_rsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStrSecurePicUrl_:1;
  BOOL hasBytesValideCodeSig_:1;
  BOOL hasBytesPicBinary_:1;
  NSString* strSecurePicUrl;
  NSData* bytesValideCodeSig;
  NSData* bytesPicBinary;
}
- (BOOL) hasStrSecurePicUrl;
- (BOOL) hasBytesValideCodeSig;
- (BOOL) hasBytesPicBinary;
@property (readonly, strong) NSString* strSecurePicUrl;
@property (readonly, strong) NSData* bytesValideCodeSig;
@property (readonly, strong) NSData* bytesPicBinary;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (get_register_page_rspBuilder*) builder;
+ (get_register_page_rspBuilder*) builder;
+ (get_register_page_rspBuilder*) builderWithPrototype:(get_register_page_rsp*) prototype;
- (get_register_page_rspBuilder*) toBuilder;

+ (get_register_page_rsp*) parseFromData:(NSData*) data;
+ (get_register_page_rsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (get_register_page_rsp*) parseFromInputStream:(NSInputStream*) input;
+ (get_register_page_rsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (get_register_page_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (get_register_page_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface get_register_page_rspBuilder : PBGeneratedMessageBuilder {
@private
  get_register_page_rsp* resultGetRegisterPageRsp;
}

- (get_register_page_rsp*) defaultInstance;

- (get_register_page_rspBuilder*) clear;
- (get_register_page_rspBuilder*) clone;

- (get_register_page_rsp*) build;
- (get_register_page_rsp*) buildPartial;

- (get_register_page_rspBuilder*) mergeFrom:(get_register_page_rsp*) other;
- (get_register_page_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (get_register_page_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStrSecurePicUrl;
- (NSString*) strSecurePicUrl;
- (get_register_page_rspBuilder*) setStrSecurePicUrl:(NSString*) value;
- (get_register_page_rspBuilder*) clearStrSecurePicUrl;

- (BOOL) hasBytesValideCodeSig;
- (NSData*) bytesValideCodeSig;
- (get_register_page_rspBuilder*) setBytesValideCodeSig:(NSData*) value;
- (get_register_page_rspBuilder*) clearBytesValideCodeSig;

- (BOOL) hasBytesPicBinary;
- (NSData*) bytesPicBinary;
- (get_register_page_rspBuilder*) setBytesPicBinary:(NSData*) value;
- (get_register_page_rspBuilder*) clearBytesPicBinary;
@end

#define register_getsms_num_req_str_phone_num @"strPhoneNum"
#define register_getsms_num_req_str_valide_code @"strValideCode"
#define register_getsms_num_req_bytes_valide_code_sig @"bytesValideCodeSig"
@interface register_getsms_num_req : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStrPhoneNum_:1;
  BOOL hasStrValideCode_:1;
  BOOL hasBytesValideCodeSig_:1;
  NSString* strPhoneNum;
  NSString* strValideCode;
  NSData* bytesValideCodeSig;
}
- (BOOL) hasStrPhoneNum;
- (BOOL) hasStrValideCode;
- (BOOL) hasBytesValideCodeSig;
@property (readonly, strong) NSString* strPhoneNum;
@property (readonly, strong) NSString* strValideCode;
@property (readonly, strong) NSData* bytesValideCodeSig;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (register_getsms_num_reqBuilder*) builder;
+ (register_getsms_num_reqBuilder*) builder;
+ (register_getsms_num_reqBuilder*) builderWithPrototype:(register_getsms_num_req*) prototype;
- (register_getsms_num_reqBuilder*) toBuilder;

+ (register_getsms_num_req*) parseFromData:(NSData*) data;
+ (register_getsms_num_req*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_getsms_num_req*) parseFromInputStream:(NSInputStream*) input;
+ (register_getsms_num_req*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_getsms_num_req*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (register_getsms_num_req*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface register_getsms_num_reqBuilder : PBGeneratedMessageBuilder {
@private
  register_getsms_num_req* resultRegisterGetsmsNumReq;
}

- (register_getsms_num_req*) defaultInstance;

- (register_getsms_num_reqBuilder*) clear;
- (register_getsms_num_reqBuilder*) clone;

- (register_getsms_num_req*) build;
- (register_getsms_num_req*) buildPartial;

- (register_getsms_num_reqBuilder*) mergeFrom:(register_getsms_num_req*) other;
- (register_getsms_num_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (register_getsms_num_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStrPhoneNum;
- (NSString*) strPhoneNum;
- (register_getsms_num_reqBuilder*) setStrPhoneNum:(NSString*) value;
- (register_getsms_num_reqBuilder*) clearStrPhoneNum;

- (BOOL) hasStrValideCode;
- (NSString*) strValideCode;
- (register_getsms_num_reqBuilder*) setStrValideCode:(NSString*) value;
- (register_getsms_num_reqBuilder*) clearStrValideCode;

- (BOOL) hasBytesValideCodeSig;
- (NSData*) bytesValideCodeSig;
- (register_getsms_num_reqBuilder*) setBytesValideCodeSig:(NSData*) value;
- (register_getsms_num_reqBuilder*) clearBytesValideCodeSig;
@end

@interface register_getsms_num_rsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (register_getsms_num_rspBuilder*) builder;
+ (register_getsms_num_rspBuilder*) builder;
+ (register_getsms_num_rspBuilder*) builderWithPrototype:(register_getsms_num_rsp*) prototype;
- (register_getsms_num_rspBuilder*) toBuilder;

+ (register_getsms_num_rsp*) parseFromData:(NSData*) data;
+ (register_getsms_num_rsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_getsms_num_rsp*) parseFromInputStream:(NSInputStream*) input;
+ (register_getsms_num_rsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_getsms_num_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (register_getsms_num_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface register_getsms_num_rspBuilder : PBGeneratedMessageBuilder {
@private
  register_getsms_num_rsp* resultRegisterGetsmsNumRsp;
}

- (register_getsms_num_rsp*) defaultInstance;

- (register_getsms_num_rspBuilder*) clear;
- (register_getsms_num_rspBuilder*) clone;

- (register_getsms_num_rsp*) build;
- (register_getsms_num_rsp*) buildPartial;

- (register_getsms_num_rspBuilder*) mergeFrom:(register_getsms_num_rsp*) other;
- (register_getsms_num_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (register_getsms_num_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define register_req_str_phone_num @"strPhoneNum"
#define register_req_str_secure_num @"strSecureNum"
#define register_req_str_valide_code @"strValideCode"
#define register_req_bytes_valide_code_sig @"bytesValideCodeSig"
@interface register_req : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasStrPhoneNum_:1;
  BOOL hasStrSecureNum_:1;
  BOOL hasStrValideCode_:1;
  BOOL hasBytesValideCodeSig_:1;
  NSString* strPhoneNum;
  NSString* strSecureNum;
  NSString* strValideCode;
  NSData* bytesValideCodeSig;
}
- (BOOL) hasStrPhoneNum;
- (BOOL) hasStrSecureNum;
- (BOOL) hasStrValideCode;
- (BOOL) hasBytesValideCodeSig;
@property (readonly, strong) NSString* strPhoneNum;
@property (readonly, strong) NSString* strSecureNum;
@property (readonly, strong) NSString* strValideCode;
@property (readonly, strong) NSData* bytesValideCodeSig;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (register_reqBuilder*) builder;
+ (register_reqBuilder*) builder;
+ (register_reqBuilder*) builderWithPrototype:(register_req*) prototype;
- (register_reqBuilder*) toBuilder;

+ (register_req*) parseFromData:(NSData*) data;
+ (register_req*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_req*) parseFromInputStream:(NSInputStream*) input;
+ (register_req*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_req*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (register_req*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface register_reqBuilder : PBGeneratedMessageBuilder {
@private
  register_req* resultRegisterReq;
}

- (register_req*) defaultInstance;

- (register_reqBuilder*) clear;
- (register_reqBuilder*) clone;

- (register_req*) build;
- (register_req*) buildPartial;

- (register_reqBuilder*) mergeFrom:(register_req*) other;
- (register_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (register_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStrPhoneNum;
- (NSString*) strPhoneNum;
- (register_reqBuilder*) setStrPhoneNum:(NSString*) value;
- (register_reqBuilder*) clearStrPhoneNum;

- (BOOL) hasStrSecureNum;
- (NSString*) strSecureNum;
- (register_reqBuilder*) setStrSecureNum:(NSString*) value;
- (register_reqBuilder*) clearStrSecureNum;

- (BOOL) hasStrValideCode;
- (NSString*) strValideCode;
- (register_reqBuilder*) setStrValideCode:(NSString*) value;
- (register_reqBuilder*) clearStrValideCode;

- (BOOL) hasBytesValideCodeSig;
- (NSData*) bytesValideCodeSig;
- (register_reqBuilder*) setBytesValideCodeSig:(NSData*) value;
- (register_reqBuilder*) clearBytesValideCodeSig;
@end

#define register_rsp_int32_uid @"int32Uid"
@interface register_rsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasInt32Uid_:1;
  SInt32 int32Uid;
}
- (BOOL) hasInt32Uid;
@property (readonly) SInt32 int32Uid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (register_rspBuilder*) builder;
+ (register_rspBuilder*) builder;
+ (register_rspBuilder*) builderWithPrototype:(register_rsp*) prototype;
- (register_rspBuilder*) toBuilder;

+ (register_rsp*) parseFromData:(NSData*) data;
+ (register_rsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_rsp*) parseFromInputStream:(NSInputStream*) input;
+ (register_rsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (register_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface register_rspBuilder : PBGeneratedMessageBuilder {
@private
  register_rsp* resultRegisterRsp;
}

- (register_rsp*) defaultInstance;

- (register_rspBuilder*) clear;
- (register_rspBuilder*) clone;

- (register_rsp*) build;
- (register_rsp*) buildPartial;

- (register_rspBuilder*) mergeFrom:(register_rsp*) other;
- (register_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (register_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasInt32Uid;
- (SInt32) int32Uid;
- (register_rspBuilder*) setInt32Uid:(SInt32) value;
- (register_rspBuilder*) clearInt32Uid;
@end

#define register_set_passwd_req_int32_uid @"int32Uid"
#define register_set_passwd_req_bytes_passwd_md5_salt @"bytesPasswdMd5Salt"
#define register_set_passwd_req_str_phone_num @"strPhoneNum"
@interface register_set_passwd_req : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasInt32Uid_:1;
  BOOL hasStrPhoneNum_:1;
  BOOL hasBytesPasswdMd5Salt_:1;
  SInt32 int32Uid;
  NSString* strPhoneNum;
  NSData* bytesPasswdMd5Salt;
}
- (BOOL) hasInt32Uid;
- (BOOL) hasBytesPasswdMd5Salt;
- (BOOL) hasStrPhoneNum;
@property (readonly) SInt32 int32Uid;
@property (readonly, strong) NSData* bytesPasswdMd5Salt;
@property (readonly, strong) NSString* strPhoneNum;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (register_set_passwd_reqBuilder*) builder;
+ (register_set_passwd_reqBuilder*) builder;
+ (register_set_passwd_reqBuilder*) builderWithPrototype:(register_set_passwd_req*) prototype;
- (register_set_passwd_reqBuilder*) toBuilder;

+ (register_set_passwd_req*) parseFromData:(NSData*) data;
+ (register_set_passwd_req*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_set_passwd_req*) parseFromInputStream:(NSInputStream*) input;
+ (register_set_passwd_req*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_set_passwd_req*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (register_set_passwd_req*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface register_set_passwd_reqBuilder : PBGeneratedMessageBuilder {
@private
  register_set_passwd_req* resultRegisterSetPasswdReq;
}

- (register_set_passwd_req*) defaultInstance;

- (register_set_passwd_reqBuilder*) clear;
- (register_set_passwd_reqBuilder*) clone;

- (register_set_passwd_req*) build;
- (register_set_passwd_req*) buildPartial;

- (register_set_passwd_reqBuilder*) mergeFrom:(register_set_passwd_req*) other;
- (register_set_passwd_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (register_set_passwd_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasInt32Uid;
- (SInt32) int32Uid;
- (register_set_passwd_reqBuilder*) setInt32Uid:(SInt32) value;
- (register_set_passwd_reqBuilder*) clearInt32Uid;

- (BOOL) hasBytesPasswdMd5Salt;
- (NSData*) bytesPasswdMd5Salt;
- (register_set_passwd_reqBuilder*) setBytesPasswdMd5Salt:(NSData*) value;
- (register_set_passwd_reqBuilder*) clearBytesPasswdMd5Salt;

- (BOOL) hasStrPhoneNum;
- (NSString*) strPhoneNum;
- (register_set_passwd_reqBuilder*) setStrPhoneNum:(NSString*) value;
- (register_set_passwd_reqBuilder*) clearStrPhoneNum;
@end

@interface register_set_passwd_rsp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (register_set_passwd_rspBuilder*) builder;
+ (register_set_passwd_rspBuilder*) builder;
+ (register_set_passwd_rspBuilder*) builderWithPrototype:(register_set_passwd_rsp*) prototype;
- (register_set_passwd_rspBuilder*) toBuilder;

+ (register_set_passwd_rsp*) parseFromData:(NSData*) data;
+ (register_set_passwd_rsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_set_passwd_rsp*) parseFromInputStream:(NSInputStream*) input;
+ (register_set_passwd_rsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (register_set_passwd_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (register_set_passwd_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface register_set_passwd_rspBuilder : PBGeneratedMessageBuilder {
@private
  register_set_passwd_rsp* resultRegisterSetPasswdRsp;
}

- (register_set_passwd_rsp*) defaultInstance;

- (register_set_passwd_rspBuilder*) clear;
- (register_set_passwd_rspBuilder*) clone;

- (register_set_passwd_rsp*) build;
- (register_set_passwd_rsp*) buildPartial;

- (register_set_passwd_rspBuilder*) mergeFrom:(register_set_passwd_rsp*) other;
- (register_set_passwd_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (register_set_passwd_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end


// @@protoc_insertion_point(global_scope)
