// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class CSHead;
@class CSHeadBuilder;
@class Head;
@class HeadBuilder;
@class LoginSig;
@class LoginSigBuilder;



@interface ZsappImMsgHeadRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Head_int32_module_id @"int32ModuleId"
#define Head_int32_head_type @"int32HeadType"
#define Head_msg_cshead @"msgCshead"
#define Head_msg_login_sig @"msgLoginSig"
@interface Head : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasInt32ModuleId_:1;
  BOOL hasInt32HeadType_:1;
  BOOL hasMsgCshead_:1;
  BOOL hasMsgLoginSig_:1;
  SInt32 int32ModuleId;
  SInt32 int32HeadType;
  CSHead* msgCshead;
  LoginSig* msgLoginSig;
}
- (BOOL) hasInt32ModuleId;
- (BOOL) hasInt32HeadType;
- (BOOL) hasMsgCshead;
- (BOOL) hasMsgLoginSig;
@property (readonly) SInt32 int32ModuleId;
@property (readonly) SInt32 int32HeadType;
@property (readonly, strong) CSHead* msgCshead;
@property (readonly, strong) LoginSig* msgLoginSig;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HeadBuilder*) builder;
+ (HeadBuilder*) builder;
+ (HeadBuilder*) builderWithPrototype:(Head*) prototype;
- (HeadBuilder*) toBuilder;

+ (Head*) parseFromData:(NSData*) data;
+ (Head*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Head*) parseFromInputStream:(NSInputStream*) input;
+ (Head*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Head*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Head*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HeadBuilder : PBGeneratedMessageBuilder {
@private
  Head* resultHead;
}

- (Head*) defaultInstance;

- (HeadBuilder*) clear;
- (HeadBuilder*) clone;

- (Head*) build;
- (Head*) buildPartial;

- (HeadBuilder*) mergeFrom:(Head*) other;
- (HeadBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HeadBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasInt32ModuleId;
- (SInt32) int32ModuleId;
- (HeadBuilder*) setInt32ModuleId:(SInt32) value;
- (HeadBuilder*) clearInt32ModuleId;

- (BOOL) hasInt32HeadType;
- (SInt32) int32HeadType;
- (HeadBuilder*) setInt32HeadType:(SInt32) value;
- (HeadBuilder*) clearInt32HeadType;

- (BOOL) hasMsgCshead;
- (CSHead*) msgCshead;
- (HeadBuilder*) setMsgCshead:(CSHead*) value;
- (HeadBuilder*) setMsgCsheadBuilder:(CSHeadBuilder*) builderForValue;
- (HeadBuilder*) mergeMsgCshead:(CSHead*) value;
- (HeadBuilder*) clearMsgCshead;

- (BOOL) hasMsgLoginSig;
- (LoginSig*) msgLoginSig;
- (HeadBuilder*) setMsgLoginSig:(LoginSig*) value;
- (HeadBuilder*) setMsgLoginSigBuilder:(LoginSigBuilder*) builderForValue;
- (HeadBuilder*) mergeMsgLoginSig:(LoginSig*) value;
- (HeadBuilder*) clearMsgLoginSig;
@end

#define CSHead_int32_version @"int32Version"
#define CSHead_int32_from_uid @"int32FromUid"
#define CSHead_int32_maincmd @"int32Maincmd"
#define CSHead_int32_subcmd @"int32Subcmd"
#define CSHead_int32_msg_seq @"int32MsgSeq"
#define CSHead_uint32_retry_times @"uint32RetryTimes"
#define CSHead_uint32_session_id @"uint32SessionId"
#define CSHead_uint32_result_code @"uint32ResultCode"
#define CSHead_uint32_result_subcode @"uint32ResultSubcode"
#define CSHead_str_error_msg @"strErrorMsg"
#define CSHead_client_ip @"clientIp"
#define CSHead_client_port @"clientPort"
#define CSHead_int32_to_uid @"int32ToUid"
#define CSHead_str_phone_num @"strPhoneNum"
#define CSHead_str_os_version @"strOsVersion"
@interface CSHead : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasInt32Version_:1;
  BOOL hasInt32FromUid_:1;
  BOOL hasInt32Maincmd_:1;
  BOOL hasInt32Subcmd_:1;
  BOOL hasInt32MsgSeq_:1;
  BOOL hasInt32ToUid_:1;
  BOOL hasStrErrorMsg_:1;
  BOOL hasClientIp_:1;
  BOOL hasStrPhoneNum_:1;
  BOOL hasStrOsVersion_:1;
  BOOL hasUint32RetryTimes_:1;
  BOOL hasUint32SessionId_:1;
  BOOL hasUint32ResultCode_:1;
  BOOL hasUint32ResultSubcode_:1;
  BOOL hasClientPort_:1;
  SInt32 int32Version;
  SInt32 int32FromUid;
  SInt32 int32Maincmd;
  SInt32 int32Subcmd;
  SInt32 int32MsgSeq;
  SInt32 int32ToUid;
  NSString* strErrorMsg;
  NSString* clientIp;
  NSString* strPhoneNum;
  NSString* strOsVersion;
  UInt32 uint32RetryTimes;
  UInt32 uint32SessionId;
  UInt32 uint32ResultCode;
  UInt32 uint32ResultSubcode;
  UInt32 clientPort;
}
- (BOOL) hasInt32Version;
- (BOOL) hasInt32FromUid;
- (BOOL) hasInt32Maincmd;
- (BOOL) hasInt32Subcmd;
- (BOOL) hasInt32MsgSeq;
- (BOOL) hasUint32RetryTimes;
- (BOOL) hasUint32SessionId;
- (BOOL) hasUint32ResultCode;
- (BOOL) hasUint32ResultSubcode;
- (BOOL) hasStrErrorMsg;
- (BOOL) hasClientIp;
- (BOOL) hasClientPort;
- (BOOL) hasInt32ToUid;
- (BOOL) hasStrPhoneNum;
- (BOOL) hasStrOsVersion;
@property (readonly) SInt32 int32Version;
@property (readonly) SInt32 int32FromUid;
@property (readonly) SInt32 int32Maincmd;
@property (readonly) SInt32 int32Subcmd;
@property (readonly) SInt32 int32MsgSeq;
@property (readonly) UInt32 uint32RetryTimes;
@property (readonly) UInt32 uint32SessionId;
@property (readonly) UInt32 uint32ResultCode;
@property (readonly) UInt32 uint32ResultSubcode;
@property (readonly, strong) NSString* strErrorMsg;
@property (readonly, strong) NSString* clientIp;
@property (readonly) UInt32 clientPort;
@property (readonly) SInt32 int32ToUid;
@property (readonly, strong) NSString* strPhoneNum;
@property (readonly, strong) NSString* strOsVersion;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CSHeadBuilder*) builder;
+ (CSHeadBuilder*) builder;
+ (CSHeadBuilder*) builderWithPrototype:(CSHead*) prototype;
- (CSHeadBuilder*) toBuilder;

+ (CSHead*) parseFromData:(NSData*) data;
+ (CSHead*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CSHead*) parseFromInputStream:(NSInputStream*) input;
+ (CSHead*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CSHead*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CSHead*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CSHeadBuilder : PBGeneratedMessageBuilder {
@private
  CSHead* resultCshead;
}

- (CSHead*) defaultInstance;

- (CSHeadBuilder*) clear;
- (CSHeadBuilder*) clone;

- (CSHead*) build;
- (CSHead*) buildPartial;

- (CSHeadBuilder*) mergeFrom:(CSHead*) other;
- (CSHeadBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CSHeadBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasInt32Version;
- (SInt32) int32Version;
- (CSHeadBuilder*) setInt32Version:(SInt32) value;
- (CSHeadBuilder*) clearInt32Version;

- (BOOL) hasInt32FromUid;
- (SInt32) int32FromUid;
- (CSHeadBuilder*) setInt32FromUid:(SInt32) value;
- (CSHeadBuilder*) clearInt32FromUid;

- (BOOL) hasInt32Maincmd;
- (SInt32) int32Maincmd;
- (CSHeadBuilder*) setInt32Maincmd:(SInt32) value;
- (CSHeadBuilder*) clearInt32Maincmd;

- (BOOL) hasInt32Subcmd;
- (SInt32) int32Subcmd;
- (CSHeadBuilder*) setInt32Subcmd:(SInt32) value;
- (CSHeadBuilder*) clearInt32Subcmd;

- (BOOL) hasInt32MsgSeq;
- (SInt32) int32MsgSeq;
- (CSHeadBuilder*) setInt32MsgSeq:(SInt32) value;
- (CSHeadBuilder*) clearInt32MsgSeq;

- (BOOL) hasUint32RetryTimes;
- (UInt32) uint32RetryTimes;
- (CSHeadBuilder*) setUint32RetryTimes:(UInt32) value;
- (CSHeadBuilder*) clearUint32RetryTimes;

- (BOOL) hasUint32SessionId;
- (UInt32) uint32SessionId;
- (CSHeadBuilder*) setUint32SessionId:(UInt32) value;
- (CSHeadBuilder*) clearUint32SessionId;

- (BOOL) hasUint32ResultCode;
- (UInt32) uint32ResultCode;
- (CSHeadBuilder*) setUint32ResultCode:(UInt32) value;
- (CSHeadBuilder*) clearUint32ResultCode;

- (BOOL) hasUint32ResultSubcode;
- (UInt32) uint32ResultSubcode;
- (CSHeadBuilder*) setUint32ResultSubcode:(UInt32) value;
- (CSHeadBuilder*) clearUint32ResultSubcode;

- (BOOL) hasStrErrorMsg;
- (NSString*) strErrorMsg;
- (CSHeadBuilder*) setStrErrorMsg:(NSString*) value;
- (CSHeadBuilder*) clearStrErrorMsg;

- (BOOL) hasClientIp;
- (NSString*) clientIp;
- (CSHeadBuilder*) setClientIp:(NSString*) value;
- (CSHeadBuilder*) clearClientIp;

- (BOOL) hasClientPort;
- (UInt32) clientPort;
- (CSHeadBuilder*) setClientPort:(UInt32) value;
- (CSHeadBuilder*) clearClientPort;

- (BOOL) hasInt32ToUid;
- (SInt32) int32ToUid;
- (CSHeadBuilder*) setInt32ToUid:(SInt32) value;
- (CSHeadBuilder*) clearInt32ToUid;

- (BOOL) hasStrPhoneNum;
- (NSString*) strPhoneNum;
- (CSHeadBuilder*) setStrPhoneNum:(NSString*) value;
- (CSHeadBuilder*) clearStrPhoneNum;

- (BOOL) hasStrOsVersion;
- (NSString*) strOsVersion;
- (CSHeadBuilder*) setStrOsVersion:(NSString*) value;
- (CSHeadBuilder*) clearStrOsVersion;
@end

#define LoginSig_int32_sig_type @"int32SigType"
#define LoginSig_bytes_sig @"bytesSig"
@interface LoginSig : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasInt32SigType_:1;
  BOOL hasBytesSig_:1;
  SInt32 int32SigType;
  NSData* bytesSig;
}
- (BOOL) hasInt32SigType;
- (BOOL) hasBytesSig;
@property (readonly) SInt32 int32SigType;
@property (readonly, strong) NSData* bytesSig;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LoginSigBuilder*) builder;
+ (LoginSigBuilder*) builder;
+ (LoginSigBuilder*) builderWithPrototype:(LoginSig*) prototype;
- (LoginSigBuilder*) toBuilder;

+ (LoginSig*) parseFromData:(NSData*) data;
+ (LoginSig*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoginSig*) parseFromInputStream:(NSInputStream*) input;
+ (LoginSig*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (LoginSig*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (LoginSig*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LoginSigBuilder : PBGeneratedMessageBuilder {
@private
  LoginSig* resultLoginSig;
}

- (LoginSig*) defaultInstance;

- (LoginSigBuilder*) clear;
- (LoginSigBuilder*) clone;

- (LoginSig*) build;
- (LoginSig*) buildPartial;

- (LoginSigBuilder*) mergeFrom:(LoginSig*) other;
- (LoginSigBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LoginSigBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasInt32SigType;
- (SInt32) int32SigType;
- (LoginSigBuilder*) setInt32SigType:(SInt32) value;
- (LoginSigBuilder*) clearInt32SigType;

- (BOOL) hasBytesSig;
- (NSData*) bytesSig;
- (LoginSigBuilder*) setBytesSig:(NSData*) value;
- (LoginSigBuilder*) clearBytesSig;
@end


// @@protoc_insertion_point(global_scope)
