// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Zsapp_im_msg_register.pb.h"
// @@protoc_insertion_point(imports)

@implementation ZsappImMsgRegisterRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ZsappImMsgRegisterRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface get_register_page_req ()
@end

@implementation get_register_page_req

- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static get_register_page_req* defaultget_register_page_reqInstance = nil;
+ (void) initialize {
  if (self == [get_register_page_req class]) {
    defaultget_register_page_reqInstance = [[get_register_page_req alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultget_register_page_reqInstance;
}
- (instancetype) defaultInstance {
  return defaultget_register_page_reqInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (get_register_page_req*) parseFromData:(NSData*) data {
  return (get_register_page_req*)[[[get_register_page_req builder] mergeFromData:data] build];
}
+ (get_register_page_req*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (get_register_page_req*)[[[get_register_page_req builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (get_register_page_req*) parseFromInputStream:(NSInputStream*) input {
  return (get_register_page_req*)[[[get_register_page_req builder] mergeFromInputStream:input] build];
}
+ (get_register_page_req*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (get_register_page_req*)[[[get_register_page_req builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (get_register_page_req*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (get_register_page_req*)[[[get_register_page_req builder] mergeFromCodedInputStream:input] build];
}
+ (get_register_page_req*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (get_register_page_req*)[[[get_register_page_req builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (get_register_page_reqBuilder*) builder {
  return [[get_register_page_reqBuilder alloc] init];
}
+ (get_register_page_reqBuilder*) builderWithPrototype:(get_register_page_req*) prototype {
  return [[get_register_page_req builder] mergeFrom:prototype];
}
- (get_register_page_reqBuilder*) builder {
  return [get_register_page_req builder];
}
- (get_register_page_reqBuilder*) toBuilder {
  return [get_register_page_req builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[get_register_page_req class]]) {
    return NO;
  }
  get_register_page_req *otherMessage = other;
  return
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface get_register_page_reqBuilder()
@property (strong) get_register_page_req* resultGetRegisterPageReq;
@end

@implementation get_register_page_reqBuilder
@synthesize resultGetRegisterPageReq;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultGetRegisterPageReq = [[get_register_page_req alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultGetRegisterPageReq;
}
- (get_register_page_reqBuilder*) clear {
  self.resultGetRegisterPageReq = [[get_register_page_req alloc] init];
  return self;
}
- (get_register_page_reqBuilder*) clone {
  return [get_register_page_req builderWithPrototype:resultGetRegisterPageReq];
}
- (get_register_page_req*) defaultInstance {
  return [get_register_page_req defaultInstance];
}
- (get_register_page_req*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (get_register_page_req*) buildPartial {
  get_register_page_req* returnMe = resultGetRegisterPageReq;
  self.resultGetRegisterPageReq = nil;
  return returnMe;
}
- (get_register_page_reqBuilder*) mergeFrom:(get_register_page_req*) other {
  if (other == [get_register_page_req defaultInstance]) {
    return self;
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (get_register_page_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (get_register_page_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end

@interface get_register_page_rsp ()
@property (strong) NSString* strSecurePicUrl;
@property (strong) NSData* bytesValideCodeSig;
@property (strong) NSData* bytesPicBinary;
@end

@implementation get_register_page_rsp

- (BOOL) hasStrSecurePicUrl {
  return !!hasStrSecurePicUrl_;
}
- (void) setHasStrSecurePicUrl:(BOOL) _value_ {
  hasStrSecurePicUrl_ = !!_value_;
}
@synthesize strSecurePicUrl;
- (BOOL) hasBytesValideCodeSig {
  return !!hasBytesValideCodeSig_;
}
- (void) setHasBytesValideCodeSig:(BOOL) _value_ {
  hasBytesValideCodeSig_ = !!_value_;
}
@synthesize bytesValideCodeSig;
- (BOOL) hasBytesPicBinary {
  return !!hasBytesPicBinary_;
}
- (void) setHasBytesPicBinary:(BOOL) _value_ {
  hasBytesPicBinary_ = !!_value_;
}
@synthesize bytesPicBinary;
- (instancetype) init {
  if ((self = [super init])) {
    self.strSecurePicUrl = @"";
    self.bytesValideCodeSig = [NSData data];
    self.bytesPicBinary = [NSData data];
  }
  return self;
}
static get_register_page_rsp* defaultget_register_page_rspInstance = nil;
+ (void) initialize {
  if (self == [get_register_page_rsp class]) {
    defaultget_register_page_rspInstance = [[get_register_page_rsp alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultget_register_page_rspInstance;
}
- (instancetype) defaultInstance {
  return defaultget_register_page_rspInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStrSecurePicUrl) {
    [output writeString:1 value:self.strSecurePicUrl];
  }
  if (self.hasBytesValideCodeSig) {
    [output writeData:2 value:self.bytesValideCodeSig];
  }
  if (self.hasBytesPicBinary) {
    [output writeData:3 value:self.bytesPicBinary];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasStrSecurePicUrl) {
    size_ += computeStringSize(1, self.strSecurePicUrl);
  }
  if (self.hasBytesValideCodeSig) {
    size_ += computeDataSize(2, self.bytesValideCodeSig);
  }
  if (self.hasBytesPicBinary) {
    size_ += computeDataSize(3, self.bytesPicBinary);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (get_register_page_rsp*) parseFromData:(NSData*) data {
  return (get_register_page_rsp*)[[[get_register_page_rsp builder] mergeFromData:data] build];
}
+ (get_register_page_rsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (get_register_page_rsp*)[[[get_register_page_rsp builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (get_register_page_rsp*) parseFromInputStream:(NSInputStream*) input {
  return (get_register_page_rsp*)[[[get_register_page_rsp builder] mergeFromInputStream:input] build];
}
+ (get_register_page_rsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (get_register_page_rsp*)[[[get_register_page_rsp builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (get_register_page_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (get_register_page_rsp*)[[[get_register_page_rsp builder] mergeFromCodedInputStream:input] build];
}
+ (get_register_page_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (get_register_page_rsp*)[[[get_register_page_rsp builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (get_register_page_rspBuilder*) builder {
  return [[get_register_page_rspBuilder alloc] init];
}
+ (get_register_page_rspBuilder*) builderWithPrototype:(get_register_page_rsp*) prototype {
  return [[get_register_page_rsp builder] mergeFrom:prototype];
}
- (get_register_page_rspBuilder*) builder {
  return [get_register_page_rsp builder];
}
- (get_register_page_rspBuilder*) toBuilder {
  return [get_register_page_rsp builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasStrSecurePicUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"strSecurePicUrl", self.strSecurePicUrl];
  }
  if (self.hasBytesValideCodeSig) {
    [output appendFormat:@"%@%@: %@\n", indent, @"bytesValideCodeSig", self.bytesValideCodeSig];
  }
  if (self.hasBytesPicBinary) {
    [output appendFormat:@"%@%@: %@\n", indent, @"bytesPicBinary", self.bytesPicBinary];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasStrSecurePicUrl) {
    [dictionary setObject: self.strSecurePicUrl forKey: @"strSecurePicUrl"];
  }
  if (self.hasBytesValideCodeSig) {
    [dictionary setObject: self.bytesValideCodeSig forKey: @"bytesValideCodeSig"];
  }
  if (self.hasBytesPicBinary) {
    [dictionary setObject: self.bytesPicBinary forKey: @"bytesPicBinary"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[get_register_page_rsp class]]) {
    return NO;
  }
  get_register_page_rsp *otherMessage = other;
  return
      self.hasStrSecurePicUrl == otherMessage.hasStrSecurePicUrl &&
      (!self.hasStrSecurePicUrl || [self.strSecurePicUrl isEqual:otherMessage.strSecurePicUrl]) &&
      self.hasBytesValideCodeSig == otherMessage.hasBytesValideCodeSig &&
      (!self.hasBytesValideCodeSig || [self.bytesValideCodeSig isEqual:otherMessage.bytesValideCodeSig]) &&
      self.hasBytesPicBinary == otherMessage.hasBytesPicBinary &&
      (!self.hasBytesPicBinary || [self.bytesPicBinary isEqual:otherMessage.bytesPicBinary]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasStrSecurePicUrl) {
    hashCode = hashCode * 31 + [self.strSecurePicUrl hash];
  }
  if (self.hasBytesValideCodeSig) {
    hashCode = hashCode * 31 + [self.bytesValideCodeSig hash];
  }
  if (self.hasBytesPicBinary) {
    hashCode = hashCode * 31 + [self.bytesPicBinary hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface get_register_page_rspBuilder()
@property (strong) get_register_page_rsp* resultGetRegisterPageRsp;
@end

@implementation get_register_page_rspBuilder
@synthesize resultGetRegisterPageRsp;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultGetRegisterPageRsp = [[get_register_page_rsp alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultGetRegisterPageRsp;
}
- (get_register_page_rspBuilder*) clear {
  self.resultGetRegisterPageRsp = [[get_register_page_rsp alloc] init];
  return self;
}
- (get_register_page_rspBuilder*) clone {
  return [get_register_page_rsp builderWithPrototype:resultGetRegisterPageRsp];
}
- (get_register_page_rsp*) defaultInstance {
  return [get_register_page_rsp defaultInstance];
}
- (get_register_page_rsp*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (get_register_page_rsp*) buildPartial {
  get_register_page_rsp* returnMe = resultGetRegisterPageRsp;
  self.resultGetRegisterPageRsp = nil;
  return returnMe;
}
- (get_register_page_rspBuilder*) mergeFrom:(get_register_page_rsp*) other {
  if (other == [get_register_page_rsp defaultInstance]) {
    return self;
  }
  if (other.hasStrSecurePicUrl) {
    [self setStrSecurePicUrl:other.strSecurePicUrl];
  }
  if (other.hasBytesValideCodeSig) {
    [self setBytesValideCodeSig:other.bytesValideCodeSig];
  }
  if (other.hasBytesPicBinary) {
    [self setBytesPicBinary:other.bytesPicBinary];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (get_register_page_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (get_register_page_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setStrSecurePicUrl:[input readString]];
        break;
      }
      case 18: {
        [self setBytesValideCodeSig:[input readData]];
        break;
      }
      case 26: {
        [self setBytesPicBinary:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasStrSecurePicUrl {
  return resultGetRegisterPageRsp.hasStrSecurePicUrl;
}
- (NSString*) strSecurePicUrl {
  return resultGetRegisterPageRsp.strSecurePicUrl;
}
- (get_register_page_rspBuilder*) setStrSecurePicUrl:(NSString*) value {
  resultGetRegisterPageRsp.hasStrSecurePicUrl = YES;
  resultGetRegisterPageRsp.strSecurePicUrl = value;
  return self;
}
- (get_register_page_rspBuilder*) clearStrSecurePicUrl {
  resultGetRegisterPageRsp.hasStrSecurePicUrl = NO;
  resultGetRegisterPageRsp.strSecurePicUrl = @"";
  return self;
}
- (BOOL) hasBytesValideCodeSig {
  return resultGetRegisterPageRsp.hasBytesValideCodeSig;
}
- (NSData*) bytesValideCodeSig {
  return resultGetRegisterPageRsp.bytesValideCodeSig;
}
- (get_register_page_rspBuilder*) setBytesValideCodeSig:(NSData*) value {
  resultGetRegisterPageRsp.hasBytesValideCodeSig = YES;
  resultGetRegisterPageRsp.bytesValideCodeSig = value;
  return self;
}
- (get_register_page_rspBuilder*) clearBytesValideCodeSig {
  resultGetRegisterPageRsp.hasBytesValideCodeSig = NO;
  resultGetRegisterPageRsp.bytesValideCodeSig = [NSData data];
  return self;
}
- (BOOL) hasBytesPicBinary {
  return resultGetRegisterPageRsp.hasBytesPicBinary;
}
- (NSData*) bytesPicBinary {
  return resultGetRegisterPageRsp.bytesPicBinary;
}
- (get_register_page_rspBuilder*) setBytesPicBinary:(NSData*) value {
  resultGetRegisterPageRsp.hasBytesPicBinary = YES;
  resultGetRegisterPageRsp.bytesPicBinary = value;
  return self;
}
- (get_register_page_rspBuilder*) clearBytesPicBinary {
  resultGetRegisterPageRsp.hasBytesPicBinary = NO;
  resultGetRegisterPageRsp.bytesPicBinary = [NSData data];
  return self;
}
@end

@interface register_getsms_num_req ()
@property (strong) NSString* strPhoneNum;
@property (strong) NSString* strValideCode;
@property (strong) NSData* bytesValideCodeSig;
@end

@implementation register_getsms_num_req

- (BOOL) hasStrPhoneNum {
  return !!hasStrPhoneNum_;
}
- (void) setHasStrPhoneNum:(BOOL) _value_ {
  hasStrPhoneNum_ = !!_value_;
}
@synthesize strPhoneNum;
- (BOOL) hasStrValideCode {
  return !!hasStrValideCode_;
}
- (void) setHasStrValideCode:(BOOL) _value_ {
  hasStrValideCode_ = !!_value_;
}
@synthesize strValideCode;
- (BOOL) hasBytesValideCodeSig {
  return !!hasBytesValideCodeSig_;
}
- (void) setHasBytesValideCodeSig:(BOOL) _value_ {
  hasBytesValideCodeSig_ = !!_value_;
}
@synthesize bytesValideCodeSig;
- (instancetype) init {
  if ((self = [super init])) {
    self.strPhoneNum = @"";
    self.strValideCode = @"";
    self.bytesValideCodeSig = [NSData data];
  }
  return self;
}
static register_getsms_num_req* defaultregister_getsms_num_reqInstance = nil;
+ (void) initialize {
  if (self == [register_getsms_num_req class]) {
    defaultregister_getsms_num_reqInstance = [[register_getsms_num_req alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultregister_getsms_num_reqInstance;
}
- (instancetype) defaultInstance {
  return defaultregister_getsms_num_reqInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStrPhoneNum) {
    [output writeString:1 value:self.strPhoneNum];
  }
  if (self.hasStrValideCode) {
    [output writeString:2 value:self.strValideCode];
  }
  if (self.hasBytesValideCodeSig) {
    [output writeData:3 value:self.bytesValideCodeSig];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasStrPhoneNum) {
    size_ += computeStringSize(1, self.strPhoneNum);
  }
  if (self.hasStrValideCode) {
    size_ += computeStringSize(2, self.strValideCode);
  }
  if (self.hasBytesValideCodeSig) {
    size_ += computeDataSize(3, self.bytesValideCodeSig);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (register_getsms_num_req*) parseFromData:(NSData*) data {
  return (register_getsms_num_req*)[[[register_getsms_num_req builder] mergeFromData:data] build];
}
+ (register_getsms_num_req*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_getsms_num_req*)[[[register_getsms_num_req builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (register_getsms_num_req*) parseFromInputStream:(NSInputStream*) input {
  return (register_getsms_num_req*)[[[register_getsms_num_req builder] mergeFromInputStream:input] build];
}
+ (register_getsms_num_req*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_getsms_num_req*)[[[register_getsms_num_req builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_getsms_num_req*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (register_getsms_num_req*)[[[register_getsms_num_req builder] mergeFromCodedInputStream:input] build];
}
+ (register_getsms_num_req*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_getsms_num_req*)[[[register_getsms_num_req builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_getsms_num_reqBuilder*) builder {
  return [[register_getsms_num_reqBuilder alloc] init];
}
+ (register_getsms_num_reqBuilder*) builderWithPrototype:(register_getsms_num_req*) prototype {
  return [[register_getsms_num_req builder] mergeFrom:prototype];
}
- (register_getsms_num_reqBuilder*) builder {
  return [register_getsms_num_req builder];
}
- (register_getsms_num_reqBuilder*) toBuilder {
  return [register_getsms_num_req builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasStrPhoneNum) {
    [output appendFormat:@"%@%@: %@\n", indent, @"strPhoneNum", self.strPhoneNum];
  }
  if (self.hasStrValideCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"strValideCode", self.strValideCode];
  }
  if (self.hasBytesValideCodeSig) {
    [output appendFormat:@"%@%@: %@\n", indent, @"bytesValideCodeSig", self.bytesValideCodeSig];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasStrPhoneNum) {
    [dictionary setObject: self.strPhoneNum forKey: @"strPhoneNum"];
  }
  if (self.hasStrValideCode) {
    [dictionary setObject: self.strValideCode forKey: @"strValideCode"];
  }
  if (self.hasBytesValideCodeSig) {
    [dictionary setObject: self.bytesValideCodeSig forKey: @"bytesValideCodeSig"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[register_getsms_num_req class]]) {
    return NO;
  }
  register_getsms_num_req *otherMessage = other;
  return
      self.hasStrPhoneNum == otherMessage.hasStrPhoneNum &&
      (!self.hasStrPhoneNum || [self.strPhoneNum isEqual:otherMessage.strPhoneNum]) &&
      self.hasStrValideCode == otherMessage.hasStrValideCode &&
      (!self.hasStrValideCode || [self.strValideCode isEqual:otherMessage.strValideCode]) &&
      self.hasBytesValideCodeSig == otherMessage.hasBytesValideCodeSig &&
      (!self.hasBytesValideCodeSig || [self.bytesValideCodeSig isEqual:otherMessage.bytesValideCodeSig]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasStrPhoneNum) {
    hashCode = hashCode * 31 + [self.strPhoneNum hash];
  }
  if (self.hasStrValideCode) {
    hashCode = hashCode * 31 + [self.strValideCode hash];
  }
  if (self.hasBytesValideCodeSig) {
    hashCode = hashCode * 31 + [self.bytesValideCodeSig hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface register_getsms_num_reqBuilder()
@property (strong) register_getsms_num_req* resultRegisterGetsmsNumReq;
@end

@implementation register_getsms_num_reqBuilder
@synthesize resultRegisterGetsmsNumReq;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultRegisterGetsmsNumReq = [[register_getsms_num_req alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultRegisterGetsmsNumReq;
}
- (register_getsms_num_reqBuilder*) clear {
  self.resultRegisterGetsmsNumReq = [[register_getsms_num_req alloc] init];
  return self;
}
- (register_getsms_num_reqBuilder*) clone {
  return [register_getsms_num_req builderWithPrototype:resultRegisterGetsmsNumReq];
}
- (register_getsms_num_req*) defaultInstance {
  return [register_getsms_num_req defaultInstance];
}
- (register_getsms_num_req*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (register_getsms_num_req*) buildPartial {
  register_getsms_num_req* returnMe = resultRegisterGetsmsNumReq;
  self.resultRegisterGetsmsNumReq = nil;
  return returnMe;
}
- (register_getsms_num_reqBuilder*) mergeFrom:(register_getsms_num_req*) other {
  if (other == [register_getsms_num_req defaultInstance]) {
    return self;
  }
  if (other.hasStrPhoneNum) {
    [self setStrPhoneNum:other.strPhoneNum];
  }
  if (other.hasStrValideCode) {
    [self setStrValideCode:other.strValideCode];
  }
  if (other.hasBytesValideCodeSig) {
    [self setBytesValideCodeSig:other.bytesValideCodeSig];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (register_getsms_num_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (register_getsms_num_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setStrPhoneNum:[input readString]];
        break;
      }
      case 18: {
        [self setStrValideCode:[input readString]];
        break;
      }
      case 26: {
        [self setBytesValideCodeSig:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasStrPhoneNum {
  return resultRegisterGetsmsNumReq.hasStrPhoneNum;
}
- (NSString*) strPhoneNum {
  return resultRegisterGetsmsNumReq.strPhoneNum;
}
- (register_getsms_num_reqBuilder*) setStrPhoneNum:(NSString*) value {
  resultRegisterGetsmsNumReq.hasStrPhoneNum = YES;
  resultRegisterGetsmsNumReq.strPhoneNum = value;
  return self;
}
- (register_getsms_num_reqBuilder*) clearStrPhoneNum {
  resultRegisterGetsmsNumReq.hasStrPhoneNum = NO;
  resultRegisterGetsmsNumReq.strPhoneNum = @"";
  return self;
}
- (BOOL) hasStrValideCode {
  return resultRegisterGetsmsNumReq.hasStrValideCode;
}
- (NSString*) strValideCode {
  return resultRegisterGetsmsNumReq.strValideCode;
}
- (register_getsms_num_reqBuilder*) setStrValideCode:(NSString*) value {
  resultRegisterGetsmsNumReq.hasStrValideCode = YES;
  resultRegisterGetsmsNumReq.strValideCode = value;
  return self;
}
- (register_getsms_num_reqBuilder*) clearStrValideCode {
  resultRegisterGetsmsNumReq.hasStrValideCode = NO;
  resultRegisterGetsmsNumReq.strValideCode = @"";
  return self;
}
- (BOOL) hasBytesValideCodeSig {
  return resultRegisterGetsmsNumReq.hasBytesValideCodeSig;
}
- (NSData*) bytesValideCodeSig {
  return resultRegisterGetsmsNumReq.bytesValideCodeSig;
}
- (register_getsms_num_reqBuilder*) setBytesValideCodeSig:(NSData*) value {
  resultRegisterGetsmsNumReq.hasBytesValideCodeSig = YES;
  resultRegisterGetsmsNumReq.bytesValideCodeSig = value;
  return self;
}
- (register_getsms_num_reqBuilder*) clearBytesValideCodeSig {
  resultRegisterGetsmsNumReq.hasBytesValideCodeSig = NO;
  resultRegisterGetsmsNumReq.bytesValideCodeSig = [NSData data];
  return self;
}
@end

@interface register_getsms_num_rsp ()
@end

@implementation register_getsms_num_rsp

- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static register_getsms_num_rsp* defaultregister_getsms_num_rspInstance = nil;
+ (void) initialize {
  if (self == [register_getsms_num_rsp class]) {
    defaultregister_getsms_num_rspInstance = [[register_getsms_num_rsp alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultregister_getsms_num_rspInstance;
}
- (instancetype) defaultInstance {
  return defaultregister_getsms_num_rspInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (register_getsms_num_rsp*) parseFromData:(NSData*) data {
  return (register_getsms_num_rsp*)[[[register_getsms_num_rsp builder] mergeFromData:data] build];
}
+ (register_getsms_num_rsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_getsms_num_rsp*)[[[register_getsms_num_rsp builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (register_getsms_num_rsp*) parseFromInputStream:(NSInputStream*) input {
  return (register_getsms_num_rsp*)[[[register_getsms_num_rsp builder] mergeFromInputStream:input] build];
}
+ (register_getsms_num_rsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_getsms_num_rsp*)[[[register_getsms_num_rsp builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_getsms_num_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (register_getsms_num_rsp*)[[[register_getsms_num_rsp builder] mergeFromCodedInputStream:input] build];
}
+ (register_getsms_num_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_getsms_num_rsp*)[[[register_getsms_num_rsp builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_getsms_num_rspBuilder*) builder {
  return [[register_getsms_num_rspBuilder alloc] init];
}
+ (register_getsms_num_rspBuilder*) builderWithPrototype:(register_getsms_num_rsp*) prototype {
  return [[register_getsms_num_rsp builder] mergeFrom:prototype];
}
- (register_getsms_num_rspBuilder*) builder {
  return [register_getsms_num_rsp builder];
}
- (register_getsms_num_rspBuilder*) toBuilder {
  return [register_getsms_num_rsp builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[register_getsms_num_rsp class]]) {
    return NO;
  }
  register_getsms_num_rsp *otherMessage = other;
  return
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface register_getsms_num_rspBuilder()
@property (strong) register_getsms_num_rsp* resultRegisterGetsmsNumRsp;
@end

@implementation register_getsms_num_rspBuilder
@synthesize resultRegisterGetsmsNumRsp;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultRegisterGetsmsNumRsp = [[register_getsms_num_rsp alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultRegisterGetsmsNumRsp;
}
- (register_getsms_num_rspBuilder*) clear {
  self.resultRegisterGetsmsNumRsp = [[register_getsms_num_rsp alloc] init];
  return self;
}
- (register_getsms_num_rspBuilder*) clone {
  return [register_getsms_num_rsp builderWithPrototype:resultRegisterGetsmsNumRsp];
}
- (register_getsms_num_rsp*) defaultInstance {
  return [register_getsms_num_rsp defaultInstance];
}
- (register_getsms_num_rsp*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (register_getsms_num_rsp*) buildPartial {
  register_getsms_num_rsp* returnMe = resultRegisterGetsmsNumRsp;
  self.resultRegisterGetsmsNumRsp = nil;
  return returnMe;
}
- (register_getsms_num_rspBuilder*) mergeFrom:(register_getsms_num_rsp*) other {
  if (other == [register_getsms_num_rsp defaultInstance]) {
    return self;
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (register_getsms_num_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (register_getsms_num_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end

@interface register_req ()
@property (strong) NSString* strPhoneNum;
@property (strong) NSString* strSecureNum;
@property (strong) NSString* strValideCode;
@property (strong) NSData* bytesValideCodeSig;
@end

@implementation register_req

- (BOOL) hasStrPhoneNum {
  return !!hasStrPhoneNum_;
}
- (void) setHasStrPhoneNum:(BOOL) _value_ {
  hasStrPhoneNum_ = !!_value_;
}
@synthesize strPhoneNum;
- (BOOL) hasStrSecureNum {
  return !!hasStrSecureNum_;
}
- (void) setHasStrSecureNum:(BOOL) _value_ {
  hasStrSecureNum_ = !!_value_;
}
@synthesize strSecureNum;
- (BOOL) hasStrValideCode {
  return !!hasStrValideCode_;
}
- (void) setHasStrValideCode:(BOOL) _value_ {
  hasStrValideCode_ = !!_value_;
}
@synthesize strValideCode;
- (BOOL) hasBytesValideCodeSig {
  return !!hasBytesValideCodeSig_;
}
- (void) setHasBytesValideCodeSig:(BOOL) _value_ {
  hasBytesValideCodeSig_ = !!_value_;
}
@synthesize bytesValideCodeSig;
- (instancetype) init {
  if ((self = [super init])) {
    self.strPhoneNum = @"";
    self.strSecureNum = @"";
    self.strValideCode = @"";
    self.bytesValideCodeSig = [NSData data];
  }
  return self;
}
static register_req* defaultregister_reqInstance = nil;
+ (void) initialize {
  if (self == [register_req class]) {
    defaultregister_reqInstance = [[register_req alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultregister_reqInstance;
}
- (instancetype) defaultInstance {
  return defaultregister_reqInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStrPhoneNum) {
    [output writeString:1 value:self.strPhoneNum];
  }
  if (self.hasStrSecureNum) {
    [output writeString:2 value:self.strSecureNum];
  }
  if (self.hasStrValideCode) {
    [output writeString:3 value:self.strValideCode];
  }
  if (self.hasBytesValideCodeSig) {
    [output writeData:4 value:self.bytesValideCodeSig];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasStrPhoneNum) {
    size_ += computeStringSize(1, self.strPhoneNum);
  }
  if (self.hasStrSecureNum) {
    size_ += computeStringSize(2, self.strSecureNum);
  }
  if (self.hasStrValideCode) {
    size_ += computeStringSize(3, self.strValideCode);
  }
  if (self.hasBytesValideCodeSig) {
    size_ += computeDataSize(4, self.bytesValideCodeSig);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (register_req*) parseFromData:(NSData*) data {
  return (register_req*)[[[register_req builder] mergeFromData:data] build];
}
+ (register_req*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_req*)[[[register_req builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (register_req*) parseFromInputStream:(NSInputStream*) input {
  return (register_req*)[[[register_req builder] mergeFromInputStream:input] build];
}
+ (register_req*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_req*)[[[register_req builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_req*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (register_req*)[[[register_req builder] mergeFromCodedInputStream:input] build];
}
+ (register_req*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_req*)[[[register_req builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_reqBuilder*) builder {
  return [[register_reqBuilder alloc] init];
}
+ (register_reqBuilder*) builderWithPrototype:(register_req*) prototype {
  return [[register_req builder] mergeFrom:prototype];
}
- (register_reqBuilder*) builder {
  return [register_req builder];
}
- (register_reqBuilder*) toBuilder {
  return [register_req builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasStrPhoneNum) {
    [output appendFormat:@"%@%@: %@\n", indent, @"strPhoneNum", self.strPhoneNum];
  }
  if (self.hasStrSecureNum) {
    [output appendFormat:@"%@%@: %@\n", indent, @"strSecureNum", self.strSecureNum];
  }
  if (self.hasStrValideCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"strValideCode", self.strValideCode];
  }
  if (self.hasBytesValideCodeSig) {
    [output appendFormat:@"%@%@: %@\n", indent, @"bytesValideCodeSig", self.bytesValideCodeSig];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasStrPhoneNum) {
    [dictionary setObject: self.strPhoneNum forKey: @"strPhoneNum"];
  }
  if (self.hasStrSecureNum) {
    [dictionary setObject: self.strSecureNum forKey: @"strSecureNum"];
  }
  if (self.hasStrValideCode) {
    [dictionary setObject: self.strValideCode forKey: @"strValideCode"];
  }
  if (self.hasBytesValideCodeSig) {
    [dictionary setObject: self.bytesValideCodeSig forKey: @"bytesValideCodeSig"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[register_req class]]) {
    return NO;
  }
  register_req *otherMessage = other;
  return
      self.hasStrPhoneNum == otherMessage.hasStrPhoneNum &&
      (!self.hasStrPhoneNum || [self.strPhoneNum isEqual:otherMessage.strPhoneNum]) &&
      self.hasStrSecureNum == otherMessage.hasStrSecureNum &&
      (!self.hasStrSecureNum || [self.strSecureNum isEqual:otherMessage.strSecureNum]) &&
      self.hasStrValideCode == otherMessage.hasStrValideCode &&
      (!self.hasStrValideCode || [self.strValideCode isEqual:otherMessage.strValideCode]) &&
      self.hasBytesValideCodeSig == otherMessage.hasBytesValideCodeSig &&
      (!self.hasBytesValideCodeSig || [self.bytesValideCodeSig isEqual:otherMessage.bytesValideCodeSig]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasStrPhoneNum) {
    hashCode = hashCode * 31 + [self.strPhoneNum hash];
  }
  if (self.hasStrSecureNum) {
    hashCode = hashCode * 31 + [self.strSecureNum hash];
  }
  if (self.hasStrValideCode) {
    hashCode = hashCode * 31 + [self.strValideCode hash];
  }
  if (self.hasBytesValideCodeSig) {
    hashCode = hashCode * 31 + [self.bytesValideCodeSig hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface register_reqBuilder()
@property (strong) register_req* resultRegisterReq;
@end

@implementation register_reqBuilder
@synthesize resultRegisterReq;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultRegisterReq = [[register_req alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultRegisterReq;
}
- (register_reqBuilder*) clear {
  self.resultRegisterReq = [[register_req alloc] init];
  return self;
}
- (register_reqBuilder*) clone {
  return [register_req builderWithPrototype:resultRegisterReq];
}
- (register_req*) defaultInstance {
  return [register_req defaultInstance];
}
- (register_req*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (register_req*) buildPartial {
  register_req* returnMe = resultRegisterReq;
  self.resultRegisterReq = nil;
  return returnMe;
}
- (register_reqBuilder*) mergeFrom:(register_req*) other {
  if (other == [register_req defaultInstance]) {
    return self;
  }
  if (other.hasStrPhoneNum) {
    [self setStrPhoneNum:other.strPhoneNum];
  }
  if (other.hasStrSecureNum) {
    [self setStrSecureNum:other.strSecureNum];
  }
  if (other.hasStrValideCode) {
    [self setStrValideCode:other.strValideCode];
  }
  if (other.hasBytesValideCodeSig) {
    [self setBytesValideCodeSig:other.bytesValideCodeSig];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (register_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (register_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setStrPhoneNum:[input readString]];
        break;
      }
      case 18: {
        [self setStrSecureNum:[input readString]];
        break;
      }
      case 26: {
        [self setStrValideCode:[input readString]];
        break;
      }
      case 34: {
        [self setBytesValideCodeSig:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasStrPhoneNum {
  return resultRegisterReq.hasStrPhoneNum;
}
- (NSString*) strPhoneNum {
  return resultRegisterReq.strPhoneNum;
}
- (register_reqBuilder*) setStrPhoneNum:(NSString*) value {
  resultRegisterReq.hasStrPhoneNum = YES;
  resultRegisterReq.strPhoneNum = value;
  return self;
}
- (register_reqBuilder*) clearStrPhoneNum {
  resultRegisterReq.hasStrPhoneNum = NO;
  resultRegisterReq.strPhoneNum = @"";
  return self;
}
- (BOOL) hasStrSecureNum {
  return resultRegisterReq.hasStrSecureNum;
}
- (NSString*) strSecureNum {
  return resultRegisterReq.strSecureNum;
}
- (register_reqBuilder*) setStrSecureNum:(NSString*) value {
  resultRegisterReq.hasStrSecureNum = YES;
  resultRegisterReq.strSecureNum = value;
  return self;
}
- (register_reqBuilder*) clearStrSecureNum {
  resultRegisterReq.hasStrSecureNum = NO;
  resultRegisterReq.strSecureNum = @"";
  return self;
}
- (BOOL) hasStrValideCode {
  return resultRegisterReq.hasStrValideCode;
}
- (NSString*) strValideCode {
  return resultRegisterReq.strValideCode;
}
- (register_reqBuilder*) setStrValideCode:(NSString*) value {
  resultRegisterReq.hasStrValideCode = YES;
  resultRegisterReq.strValideCode = value;
  return self;
}
- (register_reqBuilder*) clearStrValideCode {
  resultRegisterReq.hasStrValideCode = NO;
  resultRegisterReq.strValideCode = @"";
  return self;
}
- (BOOL) hasBytesValideCodeSig {
  return resultRegisterReq.hasBytesValideCodeSig;
}
- (NSData*) bytesValideCodeSig {
  return resultRegisterReq.bytesValideCodeSig;
}
- (register_reqBuilder*) setBytesValideCodeSig:(NSData*) value {
  resultRegisterReq.hasBytesValideCodeSig = YES;
  resultRegisterReq.bytesValideCodeSig = value;
  return self;
}
- (register_reqBuilder*) clearBytesValideCodeSig {
  resultRegisterReq.hasBytesValideCodeSig = NO;
  resultRegisterReq.bytesValideCodeSig = [NSData data];
  return self;
}
@end

@interface register_rsp ()
@property SInt32 int32Uid;
@end

@implementation register_rsp

- (BOOL) hasInt32Uid {
  return !!hasInt32Uid_;
}
- (void) setHasInt32Uid:(BOOL) _value_ {
  hasInt32Uid_ = !!_value_;
}
@synthesize int32Uid;
- (instancetype) init {
  if ((self = [super init])) {
    self.int32Uid = 0;
  }
  return self;
}
static register_rsp* defaultregister_rspInstance = nil;
+ (void) initialize {
  if (self == [register_rsp class]) {
    defaultregister_rspInstance = [[register_rsp alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultregister_rspInstance;
}
- (instancetype) defaultInstance {
  return defaultregister_rspInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasInt32Uid) {
    [output writeInt32:1 value:self.int32Uid];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasInt32Uid) {
    size_ += computeInt32Size(1, self.int32Uid);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (register_rsp*) parseFromData:(NSData*) data {
  return (register_rsp*)[[[register_rsp builder] mergeFromData:data] build];
}
+ (register_rsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_rsp*)[[[register_rsp builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (register_rsp*) parseFromInputStream:(NSInputStream*) input {
  return (register_rsp*)[[[register_rsp builder] mergeFromInputStream:input] build];
}
+ (register_rsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_rsp*)[[[register_rsp builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (register_rsp*)[[[register_rsp builder] mergeFromCodedInputStream:input] build];
}
+ (register_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_rsp*)[[[register_rsp builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_rspBuilder*) builder {
  return [[register_rspBuilder alloc] init];
}
+ (register_rspBuilder*) builderWithPrototype:(register_rsp*) prototype {
  return [[register_rsp builder] mergeFrom:prototype];
}
- (register_rspBuilder*) builder {
  return [register_rsp builder];
}
- (register_rspBuilder*) toBuilder {
  return [register_rsp builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasInt32Uid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"int32Uid", [NSNumber numberWithInteger:self.int32Uid]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasInt32Uid) {
    [dictionary setObject: [NSNumber numberWithInteger:self.int32Uid] forKey: @"int32Uid"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[register_rsp class]]) {
    return NO;
  }
  register_rsp *otherMessage = other;
  return
      self.hasInt32Uid == otherMessage.hasInt32Uid &&
      (!self.hasInt32Uid || self.int32Uid == otherMessage.int32Uid) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasInt32Uid) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.int32Uid] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface register_rspBuilder()
@property (strong) register_rsp* resultRegisterRsp;
@end

@implementation register_rspBuilder
@synthesize resultRegisterRsp;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultRegisterRsp = [[register_rsp alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultRegisterRsp;
}
- (register_rspBuilder*) clear {
  self.resultRegisterRsp = [[register_rsp alloc] init];
  return self;
}
- (register_rspBuilder*) clone {
  return [register_rsp builderWithPrototype:resultRegisterRsp];
}
- (register_rsp*) defaultInstance {
  return [register_rsp defaultInstance];
}
- (register_rsp*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (register_rsp*) buildPartial {
  register_rsp* returnMe = resultRegisterRsp;
  self.resultRegisterRsp = nil;
  return returnMe;
}
- (register_rspBuilder*) mergeFrom:(register_rsp*) other {
  if (other == [register_rsp defaultInstance]) {
    return self;
  }
  if (other.hasInt32Uid) {
    [self setInt32Uid:other.int32Uid];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (register_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (register_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setInt32Uid:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasInt32Uid {
  return resultRegisterRsp.hasInt32Uid;
}
- (SInt32) int32Uid {
  return resultRegisterRsp.int32Uid;
}
- (register_rspBuilder*) setInt32Uid:(SInt32) value {
  resultRegisterRsp.hasInt32Uid = YES;
  resultRegisterRsp.int32Uid = value;
  return self;
}
- (register_rspBuilder*) clearInt32Uid {
  resultRegisterRsp.hasInt32Uid = NO;
  resultRegisterRsp.int32Uid = 0;
  return self;
}
@end

@interface register_set_passwd_req ()
@property SInt32 int32Uid;
@property (strong) NSData* bytesPasswdMd5Salt;
@property (strong) NSString* strPhoneNum;
@end

@implementation register_set_passwd_req

- (BOOL) hasInt32Uid {
  return !!hasInt32Uid_;
}
- (void) setHasInt32Uid:(BOOL) _value_ {
  hasInt32Uid_ = !!_value_;
}
@synthesize int32Uid;
- (BOOL) hasBytesPasswdMd5Salt {
  return !!hasBytesPasswdMd5Salt_;
}
- (void) setHasBytesPasswdMd5Salt:(BOOL) _value_ {
  hasBytesPasswdMd5Salt_ = !!_value_;
}
@synthesize bytesPasswdMd5Salt;
- (BOOL) hasStrPhoneNum {
  return !!hasStrPhoneNum_;
}
- (void) setHasStrPhoneNum:(BOOL) _value_ {
  hasStrPhoneNum_ = !!_value_;
}
@synthesize strPhoneNum;
- (instancetype) init {
  if ((self = [super init])) {
    self.int32Uid = 0;
    self.bytesPasswdMd5Salt = [NSData data];
    self.strPhoneNum = @"";
  }
  return self;
}
static register_set_passwd_req* defaultregister_set_passwd_reqInstance = nil;
+ (void) initialize {
  if (self == [register_set_passwd_req class]) {
    defaultregister_set_passwd_reqInstance = [[register_set_passwd_req alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultregister_set_passwd_reqInstance;
}
- (instancetype) defaultInstance {
  return defaultregister_set_passwd_reqInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasInt32Uid) {
    [output writeInt32:1 value:self.int32Uid];
  }
  if (self.hasBytesPasswdMd5Salt) {
    [output writeData:2 value:self.bytesPasswdMd5Salt];
  }
  if (self.hasStrPhoneNum) {
    [output writeString:3 value:self.strPhoneNum];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasInt32Uid) {
    size_ += computeInt32Size(1, self.int32Uid);
  }
  if (self.hasBytesPasswdMd5Salt) {
    size_ += computeDataSize(2, self.bytesPasswdMd5Salt);
  }
  if (self.hasStrPhoneNum) {
    size_ += computeStringSize(3, self.strPhoneNum);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (register_set_passwd_req*) parseFromData:(NSData*) data {
  return (register_set_passwd_req*)[[[register_set_passwd_req builder] mergeFromData:data] build];
}
+ (register_set_passwd_req*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_set_passwd_req*)[[[register_set_passwd_req builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (register_set_passwd_req*) parseFromInputStream:(NSInputStream*) input {
  return (register_set_passwd_req*)[[[register_set_passwd_req builder] mergeFromInputStream:input] build];
}
+ (register_set_passwd_req*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_set_passwd_req*)[[[register_set_passwd_req builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_set_passwd_req*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (register_set_passwd_req*)[[[register_set_passwd_req builder] mergeFromCodedInputStream:input] build];
}
+ (register_set_passwd_req*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_set_passwd_req*)[[[register_set_passwd_req builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_set_passwd_reqBuilder*) builder {
  return [[register_set_passwd_reqBuilder alloc] init];
}
+ (register_set_passwd_reqBuilder*) builderWithPrototype:(register_set_passwd_req*) prototype {
  return [[register_set_passwd_req builder] mergeFrom:prototype];
}
- (register_set_passwd_reqBuilder*) builder {
  return [register_set_passwd_req builder];
}
- (register_set_passwd_reqBuilder*) toBuilder {
  return [register_set_passwd_req builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasInt32Uid) {
    [output appendFormat:@"%@%@: %@\n", indent, @"int32Uid", [NSNumber numberWithInteger:self.int32Uid]];
  }
  if (self.hasBytesPasswdMd5Salt) {
    [output appendFormat:@"%@%@: %@\n", indent, @"bytesPasswdMd5Salt", self.bytesPasswdMd5Salt];
  }
  if (self.hasStrPhoneNum) {
    [output appendFormat:@"%@%@: %@\n", indent, @"strPhoneNum", self.strPhoneNum];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasInt32Uid) {
    [dictionary setObject: [NSNumber numberWithInteger:self.int32Uid] forKey: @"int32Uid"];
  }
  if (self.hasBytesPasswdMd5Salt) {
    [dictionary setObject: self.bytesPasswdMd5Salt forKey: @"bytesPasswdMd5Salt"];
  }
  if (self.hasStrPhoneNum) {
    [dictionary setObject: self.strPhoneNum forKey: @"strPhoneNum"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[register_set_passwd_req class]]) {
    return NO;
  }
  register_set_passwd_req *otherMessage = other;
  return
      self.hasInt32Uid == otherMessage.hasInt32Uid &&
      (!self.hasInt32Uid || self.int32Uid == otherMessage.int32Uid) &&
      self.hasBytesPasswdMd5Salt == otherMessage.hasBytesPasswdMd5Salt &&
      (!self.hasBytesPasswdMd5Salt || [self.bytesPasswdMd5Salt isEqual:otherMessage.bytesPasswdMd5Salt]) &&
      self.hasStrPhoneNum == otherMessage.hasStrPhoneNum &&
      (!self.hasStrPhoneNum || [self.strPhoneNum isEqual:otherMessage.strPhoneNum]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasInt32Uid) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.int32Uid] hash];
  }
  if (self.hasBytesPasswdMd5Salt) {
    hashCode = hashCode * 31 + [self.bytesPasswdMd5Salt hash];
  }
  if (self.hasStrPhoneNum) {
    hashCode = hashCode * 31 + [self.strPhoneNum hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface register_set_passwd_reqBuilder()
@property (strong) register_set_passwd_req* resultRegisterSetPasswdReq;
@end

@implementation register_set_passwd_reqBuilder
@synthesize resultRegisterSetPasswdReq;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultRegisterSetPasswdReq = [[register_set_passwd_req alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultRegisterSetPasswdReq;
}
- (register_set_passwd_reqBuilder*) clear {
  self.resultRegisterSetPasswdReq = [[register_set_passwd_req alloc] init];
  return self;
}
- (register_set_passwd_reqBuilder*) clone {
  return [register_set_passwd_req builderWithPrototype:resultRegisterSetPasswdReq];
}
- (register_set_passwd_req*) defaultInstance {
  return [register_set_passwd_req defaultInstance];
}
- (register_set_passwd_req*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (register_set_passwd_req*) buildPartial {
  register_set_passwd_req* returnMe = resultRegisterSetPasswdReq;
  self.resultRegisterSetPasswdReq = nil;
  return returnMe;
}
- (register_set_passwd_reqBuilder*) mergeFrom:(register_set_passwd_req*) other {
  if (other == [register_set_passwd_req defaultInstance]) {
    return self;
  }
  if (other.hasInt32Uid) {
    [self setInt32Uid:other.int32Uid];
  }
  if (other.hasBytesPasswdMd5Salt) {
    [self setBytesPasswdMd5Salt:other.bytesPasswdMd5Salt];
  }
  if (other.hasStrPhoneNum) {
    [self setStrPhoneNum:other.strPhoneNum];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (register_set_passwd_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (register_set_passwd_reqBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setInt32Uid:[input readInt32]];
        break;
      }
      case 18: {
        [self setBytesPasswdMd5Salt:[input readData]];
        break;
      }
      case 26: {
        [self setStrPhoneNum:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasInt32Uid {
  return resultRegisterSetPasswdReq.hasInt32Uid;
}
- (SInt32) int32Uid {
  return resultRegisterSetPasswdReq.int32Uid;
}
- (register_set_passwd_reqBuilder*) setInt32Uid:(SInt32) value {
  resultRegisterSetPasswdReq.hasInt32Uid = YES;
  resultRegisterSetPasswdReq.int32Uid = value;
  return self;
}
- (register_set_passwd_reqBuilder*) clearInt32Uid {
  resultRegisterSetPasswdReq.hasInt32Uid = NO;
  resultRegisterSetPasswdReq.int32Uid = 0;
  return self;
}
- (BOOL) hasBytesPasswdMd5Salt {
  return resultRegisterSetPasswdReq.hasBytesPasswdMd5Salt;
}
- (NSData*) bytesPasswdMd5Salt {
  return resultRegisterSetPasswdReq.bytesPasswdMd5Salt;
}
- (register_set_passwd_reqBuilder*) setBytesPasswdMd5Salt:(NSData*) value {
  resultRegisterSetPasswdReq.hasBytesPasswdMd5Salt = YES;
  resultRegisterSetPasswdReq.bytesPasswdMd5Salt = value;
  return self;
}
- (register_set_passwd_reqBuilder*) clearBytesPasswdMd5Salt {
  resultRegisterSetPasswdReq.hasBytesPasswdMd5Salt = NO;
  resultRegisterSetPasswdReq.bytesPasswdMd5Salt = [NSData data];
  return self;
}
- (BOOL) hasStrPhoneNum {
  return resultRegisterSetPasswdReq.hasStrPhoneNum;
}
- (NSString*) strPhoneNum {
  return resultRegisterSetPasswdReq.strPhoneNum;
}
- (register_set_passwd_reqBuilder*) setStrPhoneNum:(NSString*) value {
  resultRegisterSetPasswdReq.hasStrPhoneNum = YES;
  resultRegisterSetPasswdReq.strPhoneNum = value;
  return self;
}
- (register_set_passwd_reqBuilder*) clearStrPhoneNum {
  resultRegisterSetPasswdReq.hasStrPhoneNum = NO;
  resultRegisterSetPasswdReq.strPhoneNum = @"";
  return self;
}
@end

@interface register_set_passwd_rsp ()
@end

@implementation register_set_passwd_rsp

- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static register_set_passwd_rsp* defaultregister_set_passwd_rspInstance = nil;
+ (void) initialize {
  if (self == [register_set_passwd_rsp class]) {
    defaultregister_set_passwd_rspInstance = [[register_set_passwd_rsp alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultregister_set_passwd_rspInstance;
}
- (instancetype) defaultInstance {
  return defaultregister_set_passwd_rspInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (register_set_passwd_rsp*) parseFromData:(NSData*) data {
  return (register_set_passwd_rsp*)[[[register_set_passwd_rsp builder] mergeFromData:data] build];
}
+ (register_set_passwd_rsp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_set_passwd_rsp*)[[[register_set_passwd_rsp builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (register_set_passwd_rsp*) parseFromInputStream:(NSInputStream*) input {
  return (register_set_passwd_rsp*)[[[register_set_passwd_rsp builder] mergeFromInputStream:input] build];
}
+ (register_set_passwd_rsp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_set_passwd_rsp*)[[[register_set_passwd_rsp builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_set_passwd_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (register_set_passwd_rsp*)[[[register_set_passwd_rsp builder] mergeFromCodedInputStream:input] build];
}
+ (register_set_passwd_rsp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (register_set_passwd_rsp*)[[[register_set_passwd_rsp builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (register_set_passwd_rspBuilder*) builder {
  return [[register_set_passwd_rspBuilder alloc] init];
}
+ (register_set_passwd_rspBuilder*) builderWithPrototype:(register_set_passwd_rsp*) prototype {
  return [[register_set_passwd_rsp builder] mergeFrom:prototype];
}
- (register_set_passwd_rspBuilder*) builder {
  return [register_set_passwd_rsp builder];
}
- (register_set_passwd_rspBuilder*) toBuilder {
  return [register_set_passwd_rsp builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[register_set_passwd_rsp class]]) {
    return NO;
  }
  register_set_passwd_rsp *otherMessage = other;
  return
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface register_set_passwd_rspBuilder()
@property (strong) register_set_passwd_rsp* resultRegisterSetPasswdRsp;
@end

@implementation register_set_passwd_rspBuilder
@synthesize resultRegisterSetPasswdRsp;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultRegisterSetPasswdRsp = [[register_set_passwd_rsp alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultRegisterSetPasswdRsp;
}
- (register_set_passwd_rspBuilder*) clear {
  self.resultRegisterSetPasswdRsp = [[register_set_passwd_rsp alloc] init];
  return self;
}
- (register_set_passwd_rspBuilder*) clone {
  return [register_set_passwd_rsp builderWithPrototype:resultRegisterSetPasswdRsp];
}
- (register_set_passwd_rsp*) defaultInstance {
  return [register_set_passwd_rsp defaultInstance];
}
- (register_set_passwd_rsp*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (register_set_passwd_rsp*) buildPartial {
  register_set_passwd_rsp* returnMe = resultRegisterSetPasswdRsp;
  self.resultRegisterSetPasswdRsp = nil;
  return returnMe;
}
- (register_set_passwd_rspBuilder*) mergeFrom:(register_set_passwd_rsp*) other {
  if (other == [register_set_passwd_rsp defaultInstance]) {
    return self;
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (register_set_passwd_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (register_set_passwd_rspBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end


// @@protoc_insertion_point(global_scope)
